# Generated by Django 5.0.6 on 2026-05-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles_usuarios_prueba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['nombre'], 'permissions': [('disable_rol', 'Puede inhabilitar rol'), ('reactivate_rol', 'Puede reactivar rol')], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('disable_usuario', 'Puede inhabilitar usuario'), ('reactivate_usuario', 'Puede reactivar usuario'), ('reset_password_usuario', 'Puede resetear password de usuario')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
