# Generated by Django 5.0.14 on 2026-04-22 20:47

import apps.fichas.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolucionClinica',
            fields=[
                ('id_evolucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evolucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('anamnesis', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_cita', models.OneToOneField(db_column='id_cita', on_delete=django.db.models.deletion.RESTRICT, related_name='evolucion', to='agenda.cita')),
            ],
            options={
                'verbose_name': 'Evolución Clínica',
                'verbose_name_plural': 'Evoluciones Clínicas',
                'db_table': 'evoluciones_clinicas',
                'ordering': ['-fecha_evolucion'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoClinico',
            fields=[
                ('id_adjunto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=150)),
                ('ruta_archivo', models.FileField(max_length=255, upload_to=apps.fichas.models.adjunto_upload_path)),
                ('tipo_mime', models.CharField(max_length=80)),
                ('tamano_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_usuario_sube', models.ForeignKey(db_column='id_usuario_sube', on_delete=django.db.models.deletion.RESTRICT, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL)),
                ('id_evolucion', models.ForeignKey(db_column='id_evolucion', on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='fichas.evolucionclinica')),
            ],
            options={
                'verbose_name': 'Adjunto Clínico',
                'verbose_name_plural': 'Adjuntos Clínicos',
                'db_table': 'adjuntos_clinicos',
            },
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id_ficha_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('numero_ficha', models.CharField(max_length=30, unique=True)),
                ('fecha_apertura', models.DateField()),
                ('estado_ficha', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('bloqueada', 'Bloqueada')], default='activa', max_length=20)),
                ('observaciones_clinicas_generales', models.TextField(blank=True, null=True)),
                ('id_paciente', models.OneToOneField(db_column='id_paciente', on_delete=django.db.models.deletion.RESTRICT, related_name='ficha_clinica', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Ficha Clínica',
                'verbose_name_plural': 'Fichas Clínicas',
                'db_table': 'fichas_clinicas',
            },
        ),
    ]
