# Generated by Django 5.0.14 on 2026-04-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cita_idx_citas_estado_cita_idx_citas_fecha'),
        ('fichas', '0001_initial'),
        ('pacientes', '0002_paciente_idx_pacientes_persona'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evolucionclinica',
            index=models.Index(fields=['id_cita'], name='idx_evoluciones_cita'),
        ),
        migrations.AddIndex(
            model_name='fichaclinica',
            index=models.Index(fields=['id_paciente'], name='idx_fichas_paciente'),
        ),
    ]
