# Generated by Django 5.0.6 on 2026-05-07 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_evolucionclinica_campos_atencion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjuntoclinico',
            options={'permissions': [('disable_adjuntoclinico', 'Puede inhabilitar adjunto clinico'), ('reactivate_adjuntoclinico', 'Puede reactivar adjunto clinico'), ('download_adjuntoclinico', 'Puede descargar adjunto clinico')], 'verbose_name': 'Adjunto Clínico', 'verbose_name_plural': 'Adjuntos Clínicos'},
        ),
        migrations.AlterModelOptions(
            name='evolucionclinica',
            options={'ordering': ['-fecha_evolucion'], 'permissions': [('disable_evolucionclinica', 'Puede inhabilitar evolucion clinica'), ('reactivate_evolucionclinica', 'Puede reactivar evolucion clinica')], 'verbose_name': 'Evolución Clínica', 'verbose_name_plural': 'Evoluciones Clínicas'},
        ),
        migrations.AlterModelOptions(
            name='fichaclinica',
            options={'permissions': [('disable_fichaclinica', 'Puede inhabilitar ficha clinica'), ('reactivate_fichaclinica', 'Puede reactivar ficha clinica')], 'verbose_name': 'Ficha Clínica', 'verbose_name_plural': 'Fichas Clínicas'},
        ),
        migrations.AddField(
            model_name='adjuntoclinico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adjuntoclinico',
            name='fecha_inhabilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adjuntoclinico',
            name='inhabilitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inhabilitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjuntoclinico',
            name='motivo_inhabilitacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evolucionclinica',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evolucionclinica',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evolucionclinica',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evolucionclinica',
            name='fecha_inhabilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evolucionclinica',
            name='inhabilitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inhabilitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evolucionclinica',
            name='motivo_inhabilitacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='fecha_inhabilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='inhabilitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inhabilitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='motivo_inhabilitacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
