# Generated by Django 5.0.14 on 2026-04-22 20:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimientoCaja',
            fields=[
                ('id_tipo_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento de Caja',
                'verbose_name_plural': 'Tipos de Movimiento de Caja',
                'db_table': 'tipos_movimiento_caja',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_caja', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('id_usuario_apertura', models.ForeignKey(db_column='id_usuario_apertura', on_delete=django.db.models.deletion.RESTRICT, related_name='cajas_apertura', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_cierre', models.ForeignKey(blank=True, db_column='id_usuario_cierre', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cajas_cierre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'cajas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_movimiento_caja', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='caja.caja')),
                ('id_pago', models.OneToOneField(blank=True, db_column='id_pago', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='movimiento_caja', to='pagos.pago')),
                ('id_usuario_registra', models.ForeignKey(db_column='id_usuario_registra', on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos_caja_registrados', to=settings.AUTH_USER_MODEL)),
                ('id_tipo_movimiento', models.ForeignKey(db_column='id_tipo_movimiento', on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='caja.tipomovimientocaja')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'movimientos_caja',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['id_usuario_apertura'], name='idx_cajas_usuario_apertura'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['id_caja'], name='idx_movimientos_caja'),
        ),
    ]
