# Generated by Django 5.0.6 on 2026-05-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='diferencia_arqueo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='monto_final - saldo_calculado al cierre. Negativo = faltante, positivo = sobrante.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='observacion_cierre',
            field=models.CharField(blank=True, help_text='Justificación de diferencias en el arqueo.', max_length=300, null=True),
        ),
    ]
