# Generated by Django 5.0.6 on 2026-05-11 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_add_arqueo_fields_to_caja'),
        ('pagos', '0004_pago_chk_pago_monto_positivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaLibroMayor',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('ajuste', 'Ajuste')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_caja', models.ForeignKey(blank=True, db_column='id_caja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_libro_mayor', to='caja.caja')),
                ('id_pago', models.ForeignKey(blank=True, db_column='id_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_libro_mayor', to='pagos.pago')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, related_name='entradas_libro_mayor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada Libro Mayor',
                'verbose_name_plural': 'Libro Mayor',
                'db_table': 'libro_mayor',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='idx_libro_mayor_fecha'), models.Index(fields=['tipo'], name='idx_libro_mayor_tipo')],
            },
        ),
        migrations.AddConstraint(
            model_name='entradalibromayor',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='chk_libro_mayor_monto_positivo'),
        ),
    ]
