# Generated by Django 5.0.14 on 2026-04-22 20:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tratamientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('numero_presupuesto', models.CharField(max_length=30, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('monto_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_presupuesto', models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='vigente', max_length=20)),
                ('id_plan_tratamiento', models.ForeignKey(db_column='id_plan_tratamiento', on_delete=django.db.models.deletion.RESTRICT, related_name='presupuestos', to='tratamientos.plantratamiento')),
                ('id_usuario_emite', models.ForeignKey(db_column='id_usuario_emite', on_delete=django.db.models.deletion.RESTRICT, related_name='presupuestos_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuestos',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoDetalle',
            fields=[
                ('id_presupuesto_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_item', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_plan_detalle', models.ForeignKey(db_column='id_plan_detalle', on_delete=django.db.models.deletion.RESTRICT, related_name='presupuesto_detalles', to='tratamientos.plantratamientodetalle')),
                ('id_presupuesto', models.ForeignKey(db_column='id_presupuesto', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='presupuestos.presupuesto')),
            ],
            options={
                'verbose_name': 'Detalle de Presupuesto',
                'verbose_name_plural': 'Detalles de Presupuesto',
                'db_table': 'presupuesto_detalle',
            },
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['id_plan_tratamiento'], name='idx_presupuestos_plan'),
        ),
        migrations.AlterUniqueTogether(
            name='presupuestodetalle',
            unique_together={('id_presupuesto', 'id_plan_detalle')},
        ),
    ]
