# Generated by Django 5.0.14 on 2026-04-30 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_presupuesto_estados_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='id_usuario_anula',
            field=models.ForeignKey(blank=True, db_column='id_usuario_anula', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='presupuestos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
