# Generated by Django 5.0.6 on 2026-05-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_presupuesto_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'ordering': ['-fecha_emision'], 'permissions': [('disable_presupuesto', 'Puede anular presupuesto'), ('reactivate_presupuesto', 'Puede reactivar presupuesto')], 'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
    ]
