# Generated by Django 5.0.6 on 2026-05-07 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_alter_presupuesto_options'),
        ('tratamientos', '0005_alter_tratamiento_options_tratamiento_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='presupuesto',
            constraint=models.CheckConstraint(check=models.Q(('monto_bruto__gte', 0)), name='chk_presupuesto_monto_bruto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='presupuesto',
            constraint=models.CheckConstraint(check=models.Q(('descuento_total__gte', 0)), name='chk_presupuesto_descuento_positivo'),
        ),
        migrations.AddConstraint(
            model_name='presupuesto',
            constraint=models.CheckConstraint(check=models.Q(('monto_final__gte', 0)), name='chk_presupuesto_monto_final_positivo'),
        ),
        migrations.AddConstraint(
            model_name='presupuestodetalle',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gte', 1)), name='chk_detalle_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='presupuestodetalle',
            constraint=models.CheckConstraint(check=models.Q(('precio_unitario__gte', 0)), name='chk_detalle_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='presupuestodetalle',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='chk_detalle_subtotal_positivo'),
        ),
    ]
