# Generated by Django 5.0.14 on 2026-04-22 20:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones_administrativas', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.RESTRICT, related_name='paciente', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
            },
        ),
    ]
