# Generated by Django 5.0.14 on 2026-04-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('personas', '0002_persona_idx_personas_rut'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['id_persona'], name='idx_pacientes_persona'),
        ),
    ]
