# Generated by Django 5.0.14 on 2026-04-22 20:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0001_initial'),
        ('odontograma', '0001_initial'),
        ('odontologos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_referencial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_estimada_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado_tratamiento', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'tratamientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id_plan_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_plan', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('anulado', 'Anulado')], default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_ficha_clinica', models.ForeignKey(db_column='id_ficha_clinica', on_delete=django.db.models.deletion.RESTRICT, related_name='planes_tratamiento', to='fichas.fichaclinica')),
                ('id_odontologo', models.ForeignKey(db_column='id_odontologo', on_delete=django.db.models.deletion.RESTRICT, related_name='planes_tratamiento', to='odontologos.odontologo')),
            ],
            options={
                'verbose_name': 'Plan de Tratamiento',
                'verbose_name_plural': 'Planes de Tratamiento',
                'db_table': 'planes_tratamiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PlanTratamientoDetalle',
            fields=[
                ('id_plan_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_detalle', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('realizado', 'Realizado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('nivel_prioridad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_pieza_dental', models.ForeignKey(blank=True, db_column='codigo_pieza_dental', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='plan_detalles', to='odontograma.piezadental')),
                ('id_plan_tratamiento', models.ForeignKey(db_column='id_plan_tratamiento', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tratamientos.plantratamiento')),
                ('id_tratamiento', models.ForeignKey(db_column='id_tratamiento', on_delete=django.db.models.deletion.RESTRICT, related_name='plan_detalles', to='tratamientos.tratamiento')),
            ],
            options={
                'verbose_name': 'Detalle de Plan de Tratamiento',
                'verbose_name_plural': 'Detalles de Plan de Tratamiento',
                'db_table': 'plan_tratamiento_detalle',
            },
        ),
        migrations.AddIndex(
            model_name='plantratamiento',
            index=models.Index(fields=['id_ficha_clinica'], name='idx_planes_ficha'),
        ),
        migrations.AddIndex(
            model_name='plantratamiento',
            index=models.Index(fields=['id_odontologo'], name='idx_planes_odontologo'),
        ),
        migrations.AddIndex(
            model_name='plantratamientodetalle',
            index=models.Index(fields=['id_plan_tratamiento'], name='idx_plan_detalle_plan'),
        ),
    ]
