# Generated by Django 5.0.6 on 2026-05-07 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0004_plantratamiento_fecha_anulacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'ordering': ['nombre'], 'permissions': [('disable_tratamiento', 'Puede inhabilitar tratamiento'), ('reactivate_tratamiento', 'Puede reactivar tratamiento')], 'verbose_name': 'Tratamiento', 'verbose_name_plural': 'Tratamientos'},
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='fecha_inhabilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='inhabilitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inhabilitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='motivo_inhabilitacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
