# Generated by Django 5.0.6 on 2026-05-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pago_trazabilidad_anulacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'permissions': [('disable_pago', 'Puede anular pago'), ('reactivate_pago', 'Puede reactivar pago')], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
