# Generated by Django 5.0.6 on 2026-05-07 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_options'),
        ('presupuestos', '0004_alter_presupuesto_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='chk_pago_monto_positivo'),
        ),
    ]
