# Generated by Django 5.0.14 on 2026-04-22 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_especialidad', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('id_odontologo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_registro', models.CharField(max_length=30, unique=True)),
                ('duracion_cita_base_min', models.PositiveSmallIntegerField()),
                ('estado_profesional', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, related_name='odontologo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Odontólogo',
                'verbose_name_plural': 'Odontólogos',
                'db_table': 'odontologos',
            },
        ),
        migrations.CreateModel(
            name='OdontologoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('especialidad', models.ForeignKey(db_column='id_especialidad', on_delete=django.db.models.deletion.RESTRICT, related_name='odontologo_especialidades', to='odontologos.especialidad')),
                ('id_odontologo', models.ForeignKey(db_column='id_odontologo', on_delete=django.db.models.deletion.CASCADE, related_name='odontologo_especialidades', to='odontologos.odontologo')),
            ],
            options={
                'verbose_name': 'Especialidad de Odontólogo',
                'verbose_name_plural': 'Especialidades de Odontólogos',
                'db_table': 'odontologo_especialidad',
                'unique_together': {('id_odontologo', 'especialidad')},
            },
        ),
        migrations.AddField(
            model_name='odontologo',
            name='especialidades',
            field=models.ManyToManyField(related_name='odontologos', through='odontologos.OdontologoEspecialidad', to='odontologos.especialidad'),
        ),
        migrations.CreateModel(
            name='HorarioOdontologo',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado_horario', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('id_odontologo', models.ForeignKey(db_column='id_odontologo', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='odontologos.odontologo')),
            ],
            options={
                'verbose_name': 'Horario de Odontólogo',
                'verbose_name_plural': 'Horarios de Odontólogos',
                'db_table': 'horarios_odontologo',
                'unique_together': {('id_odontologo', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
