# Generated by Django 5.0.14 on 2026-04-22 20:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAntecedente',
            fields=[
                ('id_catalogo_antecedente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_antecedente', models.CharField(choices=[('alergia', 'Alergia'), ('enfermedad_base', 'Enfermedad base'), ('medicamento', 'Medicamento'), ('contraindicacion', 'Contraindicación'), ('otro', 'Otro')], max_length=30)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_antecedente', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Catálogo de Antecedente',
                'verbose_name_plural': 'Catálogo de Antecedentes',
                'db_table': 'catalogo_antecedentes',
                'ordering': ['tipo_antecedente', 'nombre'],
                'unique_together': {('tipo_antecedente', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAntecedentesMedicos',
            fields=[
                ('id_registro_antecedente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.RESTRICT, related_name='registros_antecedentes', to='pacientes.paciente')),
                ('id_usuario_registra', models.ForeignKey(db_column='id_usuario_registra', on_delete=django.db.models.deletion.RESTRICT, related_name='antecedentes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Antecedentes',
                'verbose_name_plural': 'Registros de Antecedentes',
                'db_table': 'registros_antecedentes_medicos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAntecedenteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_adicional', models.CharField(blank=True, max_length=200, null=True)),
                ('id_catalogo_antecedente', models.ForeignKey(db_column='id_catalogo_antecedente', on_delete=django.db.models.deletion.RESTRICT, related_name='registros_detalle', to='antecedentes.catalogoantecedente')),
                ('id_registro_antecedente', models.ForeignKey(db_column='id_registro_antecedente', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='antecedentes.registroantecedentesmedicos')),
            ],
            options={
                'verbose_name': 'Detalle de Antecedente',
                'verbose_name_plural': 'Detalles de Antecedentes',
                'db_table': 'registro_antecedente_detalle',
            },
        ),
        migrations.AddIndex(
            model_name='registroantecedentesmedicos',
            index=models.Index(fields=['id_paciente'], name='idx_reg_antecedentes_paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='registroantecedentedetalle',
            unique_together={('id_registro_antecedente', 'id_catalogo_antecedente')},
        ),
    ]
