# Generated by Django 5.0.14 on 2026-04-22 20:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaraDental',
            fields=[
                ('id_cara_dental', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Cara Dental',
                'verbose_name_plural': 'Caras Dentales',
                'db_table': 'caras_dentales',
            },
        ),
        migrations.CreateModel(
            name='CondicionOdontologica',
            fields=[
                ('id_condicion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_condicion', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Condición Odontológica',
                'verbose_name_plural': 'Condiciones Odontológicas',
                'db_table': 'condiciones_odontologicas',
            },
        ),
        migrations.CreateModel(
            name='PiezaDental',
            fields=[
                ('codigo_pieza_dental', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado_pieza', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Pieza Dental',
                'verbose_name_plural': 'Piezas Dentales',
                'db_table': 'piezas_dentales',
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id_odontograma', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion_general', models.TextField(blank=True, null=True)),
                ('estado_odontograma', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('id_ficha_clinica', models.ForeignKey(db_column='id_ficha_clinica', on_delete=django.db.models.deletion.RESTRICT, related_name='odontogramas', to='fichas.fichaclinica')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
                'db_table': 'odontogramas',
                'ordering': ['-version'],
                'unique_together': {('id_ficha_clinica', 'version')},
            },
        ),
        migrations.CreateModel(
            name='OdontogramaDetalle',
            fields=[
                ('id_odontograma_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.CharField(blank=True, max_length=150, null=True)),
                ('id_cara_dental', models.ForeignKey(db_column='id_cara_dental', on_delete=django.db.models.deletion.RESTRICT, related_name='odontograma_detalles', to='odontograma.caradental')),
                ('id_condicion', models.ForeignKey(db_column='id_condicion', on_delete=django.db.models.deletion.RESTRICT, related_name='odontograma_detalles', to='odontograma.condicionodontologica')),
                ('id_odontograma', models.ForeignKey(db_column='id_odontograma', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='odontograma.odontograma')),
                ('codigo_pieza_dental', models.ForeignKey(db_column='codigo_pieza_dental', on_delete=django.db.models.deletion.RESTRICT, related_name='odontograma_detalles', to='odontograma.piezadental')),
            ],
            options={
                'verbose_name': 'Detalle de Odontograma',
                'verbose_name_plural': 'Detalles de Odontograma',
                'db_table': 'odontograma_detalle',
                'indexes': [models.Index(fields=['codigo_pieza_dental'], name='idx_odontograma_detalle_pieza'), models.Index(fields=['id_cara_dental'], name='idx_odontograma_detalle_cara')],
                'unique_together': {('id_odontograma', 'codigo_pieza_dental', 'id_cara_dental')},
            },
        ),
    ]
