# Generated by Django 5.0.14 on 2026-04-28 04:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOdontograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cambio', models.CharField(max_length=50)),
                ('detalle_cambio', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='odontograma.odontograma')),
                ('pieza_dental', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='odontograma.piezadental')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'odontograma_historial',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OdontogramaPieza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_general', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('extraccion_indicada', 'Extracción Indicada'), ('extraido', 'Extraído'), ('implante', 'Implante'), ('no_erupcionado', 'No Erupcionado'), ('remanente', 'Remanente Radicular')], default='presente', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_pieza_dental', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='odontograma.piezadental')),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='odontograma.odontograma')),
            ],
            options={
                'verbose_name': 'Estado de Pieza',
                'verbose_name_plural': 'Estados de Piezas',
                'db_table': 'odontograma_pieza',
                'unique_together': {('odontograma', 'codigo_pieza_dental')},
            },
        ),
        migrations.CreateModel(
            name='OdontogramaPeriodontal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movilidad', models.CharField(blank=True, max_length=20, null=True)),
                ('profundidad_sondaje', models.CharField(blank=True, max_length=50, null=True)),
                ('recesion', models.CharField(blank=True, max_length=50, null=True)),
                ('sangrado', models.BooleanField(default=False)),
                ('placa', models.BooleanField(default=False)),
                ('supuracion', models.BooleanField(default=False)),
                ('furca', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('pieza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periodonto', to='odontograma.odontogramapieza')),
            ],
            options={
                'db_table': 'odontograma_periodontal',
            },
        ),
        migrations.CreateModel(
            name='OdontogramaRaiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raiz', models.CharField(choices=[('unica', 'Única'), ('mesial', 'Mesial'), ('distal', 'Distal'), ('palatina', 'Palatina'), ('mesiovestibular', 'Mesiovestibular'), ('distovestibular', 'Distovestibular'), ('vestibular', 'Vestibular')], max_length=20)),
                ('tercio', models.CharField(choices=[('cervical', 'Cervical'), ('medio', 'Medio'), ('apical', 'Apical'), ('completo', 'Completo')], default='completo', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=150, null=True)),
                ('id_condicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='odontograma.condicionodontologica')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raices', to='odontograma.odontogramapieza')),
            ],
            options={
                'db_table': 'odontograma_raiz',
                'unique_together': {('pieza', 'raiz', 'tercio')},
            },
        ),
    ]
