# Generated by Django 5.0.14 on 2026-04-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_evolucionclinica_idx_evoluciones_cita_and_more'),
        ('odontograma', '0002_historialodontograma_odontogramapieza_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='odontograma',
            index=models.Index(fields=['id_ficha_clinica'], name='idx_odontogramas_ficha'),
        ),
    ]
