# Generated by Django 5.0.14 on 2026-05-01 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0004_contexto_clinico_y_catalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='odontogramadetalle',
            name='estado_clinico',
            field=models.CharField(choices=[('sano', 'Sano / Sin registro'), ('existente', 'Existente'), ('condicion', 'Condición detectada'), ('planificado', 'Planificado'), ('en_tratamiento', 'En tratamiento'), ('completado', 'Completado'), ('ausente', 'Ausente / Extraído'), ('extraccion_indicada', 'Extracción indicada'), ('urgencia', 'Urgencia'), ('anulado', 'Anulado')], default='condicion', max_length=30),
        ),
        migrations.AddField(
            model_name='odontogramadetalle',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odontogramadetalle',
            name='id_usuario_anula',
            field=models.ForeignKey(blank=True, db_column='id_usuario_anula', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odontograma_detalles_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odontogramadetalle',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
