# Generated by Django 5.0.14 on 2026-05-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0005_odontogramadetalle_estado_clinico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionodontologica',
            name='categoria',
            field=models.CharField(choices=[('diagnostico', 'Diagnóstico'), ('tratamiento', 'Tratamiento'), ('estado_pieza', 'Estado de pieza'), ('periodoncia', 'Periodoncia'), ('urgencia', 'Urgencia'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
