# Generated by Django 5.0.6 on 2026-05-07 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0006_condicionodontologica_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odontograma',
            options={'ordering': ['-version'], 'permissions': [('disable_odontograma', 'Puede inhabilitar odontograma'), ('reactivate_odontograma', 'Puede reactivar odontograma')], 'verbose_name': 'Odontograma', 'verbose_name_plural': 'Odontogramas'},
        ),
        migrations.AddField(
            model_name='odontograma',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='fecha_inhabilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='inhabilitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inhabilitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='motivo_inhabilitacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
