# Generated by Django 5.0.14 on 2026-04-28 03:09

import apps.imagenologia.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('fichas', '0001_initial'),
        ('odontologos', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExamenImagenologico',
            fields=[
                ('id_tipo_examen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Examen Imagenológico',
                'verbose_name_plural': 'Tipos de Examen Imagenológico',
                'db_table': 'imagenologia_tipos_examen',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoExamenImagenologico',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(max_length=500, upload_to=apps.imagenologia.models.path_archivo_examen)),
                ('nombre_original', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=20)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('peso_bytes', models.BigIntegerField()),
                ('es_principal', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='archivos_imagenologia_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Examen',
                'verbose_name_plural': 'Archivos de Examen',
                'db_table': 'imagenologia_archivos',
            },
        ),
        migrations.CreateModel(
            name='AccesoExamenImagenologico',
            fields=[
                ('id_acceso', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('visualizacion', 'Visualización'), ('descarga', 'Descarga')], max_length=20)),
                ('fecha_acceso', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='accesos_imagenologia', to=settings.AUTH_USER_MODEL)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='imagenologia.archivoexamenimagenologico')),
            ],
            options={
                'verbose_name': 'Auditoría de Acceso Imagenológico',
                'verbose_name_plural': 'Auditorías de Acceso Imagenológico',
                'db_table': 'imagenologia_accesos_auditoria',
                'ordering': ['-fecha_acceso'],
            },
        ),
        migrations.CreateModel(
            name='ExamenImagenologico',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_examen', models.DateField(default=django.utils.timezone.now)),
                ('centro_radiologico', models.CharField(blank=True, max_length=150, null=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observacion_clinica', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('finalizado', 'Finalizado'), ('anulado', 'Anulado')], default='finalizado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('study_instance_uid', models.CharField(blank=True, help_text='DICOM StudyInstanceUID', max_length=255, null=True)),
                ('orthanc_study_id', models.CharField(blank=True, help_text='ID en el servidor Orthanc PACS', max_length=255, null=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_imagenologicos', to='agenda.cita')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='examenes_creados', to=settings.AUTH_USER_MODEL)),
                ('evolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_imagenologicos', to='fichas.evolucionclinica')),
                ('ficha_clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_imagenologicos', to='fichas.fichaclinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='examenes_imagenologicos', to='pacientes.paciente')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_solicitados', to='odontologos.odontologo')),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='examenes', to='imagenologia.tipoexamenimagenologico')),
            ],
            options={
                'verbose_name': 'Examen Imagenológico',
                'verbose_name_plural': 'Exámenes Imagenológicos',
                'db_table': 'imagenologia_examenes',
                'ordering': ['-fecha_examen', '-id_examen'],
            },
        ),
        migrations.AddField(
            model_name='archivoexamenimagenologico',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='imagenologia.examenimagenologico'),
        ),
        migrations.CreateModel(
            name='ObservacionImagenologica',
            fields=[
                ('id_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.TextField()),
                ('fecha_observacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='imagenologia.examenimagenologico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='observaciones_imagenologia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación Imagenológica',
                'verbose_name_plural': 'Observaciones Imagenológicas',
                'db_table': 'imagenologia_observaciones',
                'ordering': ['-fecha_observacion'],
            },
        ),
        migrations.AddIndex(
            model_name='examenimagenologico',
            index=models.Index(fields=['paciente'], name='imagenologi_pacient_0b4832_idx'),
        ),
        migrations.AddIndex(
            model_name='examenimagenologico',
            index=models.Index(fields=['fecha_examen'], name='imagenologi_fecha_e_d95821_idx'),
        ),
    ]
