# Generated by Django 5.0.6 on 2026-05-07 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenologia', '0002_archivo_trazabilidad_logica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivoexamenimagenologico',
            options={'permissions': [('disable_archivoexamenimagenologico', 'Puede anular archivo'), ('reactivate_archivoexamenimagenologico', 'Puede reactivar archivo'), ('download_archivoexamenimagenologico', 'Puede descargar archivo')], 'verbose_name': 'Archivo de Examen', 'verbose_name_plural': 'Archivos de Examen'},
        ),
        migrations.AlterModelOptions(
            name='examenimagenologico',
            options={'ordering': ['-fecha_examen', '-id_examen'], 'permissions': [('disable_examenimagenologico', 'Puede inhabilitar examen'), ('reactivate_examenimagenologico', 'Puede reactivar examen'), ('open_viewer_examenimagenologico', 'Puede abrir visor CBCT/DICOM')], 'verbose_name': 'Examen Imagenológico', 'verbose_name_plural': 'Exámenes Imagenológicos'},
        ),
        migrations.AddField(
            model_name='examenimagenologico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examenimagenologico',
            name='fecha_inhabilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examenimagenologico',
            name='inhabilitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inhabilitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examenimagenologico',
            name='motivo_inhabilitacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
