# Generated by Django 5.0.6 on 2026-05-07 20:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenologia', '0003_alter_archivoexamenimagenologico_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDeshabilitacionImagenologia',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('motivo_resolucion', models.TextField(blank=True, null=True)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_deshabilitacion', to='imagenologia.archivoexamenimagenologico')),
                ('examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_deshabilitacion', to='imagenologia.examenimagenologico')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='solicitudes_imagen_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='solicitudes_imagen_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Deshabilitación',
                'verbose_name_plural': 'Solicitudes de Deshabilitación',
                'db_table': 'imagenologia_solicitudes_deshabilitacion',
                'ordering': ['-fecha_solicitud'],
                'permissions': [('approve_solicituddeshabilitacion', 'Puede aprobar/rechazar solicitudes de deshabilitación')],
            },
        ),
    ]
