# Generated by Django 5.0.14 on 2026-04-22 20:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odontologos', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id_box', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_box', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
                'db_table': 'box',
            },
        ),
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id_estado_cita', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Cita',
                'verbose_name_plural': 'Estados de Cita',
                'db_table': 'estados_cita',
            },
        ),
        migrations.CreateModel(
            name='TipoAtencion',
            fields=[
                ('id_tipo_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('duracion_estimada_min', models.PositiveSmallIntegerField()),
                ('estado_tipo_atencion', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Atención',
                'verbose_name_plural': 'Tipos de Atención',
                'db_table': 'tipos_atencion',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('motivo_consulta', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_box', models.ForeignKey(db_column='id_box', on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='agenda.box')),
                ('id_odontologo', models.ForeignKey(db_column='id_odontologo', on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='odontologos.odontologo')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='pacientes.paciente')),
                ('id_usuario_registra', models.ForeignKey(db_column='id_usuario_registra', on_delete=django.db.models.deletion.RESTRICT, related_name='citas_registradas', to=settings.AUTH_USER_MODEL)),
                ('id_estado_cita', models.ForeignKey(db_column='id_estado_cita', on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='agenda.estadocita')),
                ('id_tipo_atencion', models.ForeignKey(db_column='id_tipo_atencion', on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='agenda.tipoatencion')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
            },
        ),
        migrations.CreateModel(
            name='HistorialCita',
            fields=[
                ('id_historial_cita', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_cambio', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='agenda.cita')),
                ('id_estado_anterior', models.ForeignKey(blank=True, db_column='id_estado_anterior', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historial_anteriores', to='agenda.estadocita')),
                ('id_estado_nuevo', models.ForeignKey(db_column='id_estado_nuevo', on_delete=django.db.models.deletion.RESTRICT, related_name='historial_nuevos', to='agenda.estadocita')),
                ('id_usuario_responsable', models.ForeignKey(db_column='id_usuario_responsable', on_delete=django.db.models.deletion.RESTRICT, related_name='historial_citas_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cita',
                'verbose_name_plural': 'Historial de Citas',
                'db_table': 'historial_citas',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['id_paciente'], name='idx_citas_paciente'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['id_odontologo'], name='idx_citas_odontologo'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['id_box'], name='idx_citas_box'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora_inicio', 'fecha_hora_fin'], name='idx_citas_inicio_fin'),
        ),
    ]
