# Generated by Django 5.0.14 on 2026-04-29 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('odontologos', '0001_initial'),
        ('pacientes', '0002_paciente_idx_pacientes_persona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['id_estado_cita'], name='idx_citas_estado'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora_inicio'], name='idx_citas_fecha'),
        ),
    ]
