# Generated by Django 5.0.14 on 2026-04-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['rut'], name='idx_personas_rut'),
        ),
    ]
