# Generated by Django 5.0.14 on 2026-04-22 20:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=50)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('id_registro_afectado', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, related_name='bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Bitácora',
                'verbose_name_plural': 'Bitácora',
                'db_table': 'bitacora',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['id_usuario'], name='idx_bitacora_usuario')],
            },
        ),
    ]
