# Generated by Django 5.0.14 on 2026-04-29 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['id_usuario', 'fecha_evento'], name='idx_bitacora_usr_fecha'),
        ),
    ]
